version: "3.9"

services:
  database:
    image: postgres:14.2
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - database
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/smartflix
    environment:
      HOST: database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password